imagePullSecrets:
  - name: ghcr-secret
replicaCount: 1
image:
  repository: ghcr.io/shareify-project/shareify-payment-service
  pullPolicy: IfNotPresent
  tag: latest
service:
  type: ClusterIP
  port: 8000
persistence:
  size: 1Gi
  storageClass: "csi-standard"
  mountPath: /data
env:
  databasePath: "/data/payments.db"

